### ISSUE TITLE
UserNotAuthenticatedException: User not authenticated

### ISSUE THREAD

**Issue by repitch** [googlesamples/android-FingerprintDialog#41] opened 2016-11-03 09:09 UTC
Problem appears only on some devices:

- Meizu PRO 6
- HTC One M9PLUS (M9+)
- LeTV Le 1s X500

Location:
`MainActivity#initCipher(Cipher cipher, String keyName)`
line 165
when calling `cipher.init(Cipher.ENCRYPT_MODE, key);`
i got `android.security.keystore.UserNotAuthenticatedException: User not authenticated`

**Comment by vijayjangid07** [comment] 2017-02-15 12:40
I am also facing the same issue in HTC One M9PLUS.
@repitch Did you find the solution for the same.

**Comment by sickworm** [comment] 2017-05-04 10:50
me too, it seems get into a dead loop.

authenticate needs init, init needs authenticate

BTW, asymmetric key works fine, just the problem of symmetric key

**Comment by pesonsita** [comment] 2018-04-11 15:54
I have also the problem on asymmetric key :(
If I configure my KeyGenerator like this,

                KeyGenParameterSpec spec = new KeyGenParameterSpec.Builder(alias, KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT)
                        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_RSA_PKCS1)
                        .setKeySize(4096)
                        .setUserAuthenticationRequired(true)
                        .setUserAuthenticationValidityDurationSeconds(6 * 10)
                        .build();

**Comment by mlynch** [comment] 2018-06-01 17:59
Running into this as well, seems to get stuck in an auth loop occasionally . Anyone able to get around it? This is for generating an asymmetric key

**Comment by NasH5169** [comment] 2018-07-24 08:33
Same on Huawei ALE-L21. Seems to be related to the duration..? If the setUserAuthenticationValidityDurationSeconds is huge value like 30000, it's ok... Very strange.

**Comment by KimJinRyul** [comment] 2018-08-06 11:18
I am also experiencing the same issue.
This problem occurs when setUserAuthenticationValidityDurationSeconds is used.
It seems to happen when the screen unlocked time is older than specified time.

for example.. when I set 5 secs... It failed.....
but try again within 5secs after I unlock the screen... It will pass...

**Comment by yashasvigirdhar** [comment] 2018-11-25 09:58
@KimJinRyul , this is the expected behaviour of the api

**Comment by nioncode** [comment] 2019-07-27 18:34
When using `setUserAuthenticationValidityDurationSeconds`, do NOT pass a `CryptoObject` to `BiometricPrompt.authenticate`. Instead, simply attempt the cryptographic operation (including `Cipher.init`) and catch `UserNotAuthenticatedException`. When you catch the exception, show the `BiometricPrompt` and initialize the Cipher in the `onAuthenticationSucceeded` from scratch.

You only have to pass a `CryptoObject` to `BiometricPrompt.authenticate` if you do not use `setUserAuthenticationValidityDurationSeconds`, because then the user must be authenticated through the prompt for each access.

**Comment by codingjeremy** [comment] 2019-09-06 15:51
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!

**Closed as completed by codingjeremy** 2019-09-06 15:51 UTC
