### ISSUE TITLE
At least one fingerprint must be enrolled to create keys requiring user authentication for every use.

### ISSUE THREAD

**Issue by arvindlaljaiswal** [googlesamples/android-FingerprintDialog#19] opened 2015-11-04 07:01 UTC
Hi,
I have tried to work out the existing FingerPrintDialog sample(google sample) in emulator, It worked at the beginning, but when I am trying to execute the same it is throwing the following error.
Caused by: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use.
The fingerprint ID is already registered from the terminal.

**Comment by thagikura** [comment] 2015-11-04 07:03
@arvindlaljaiswal 

Closing this. It's the duplicate of #18.
I think it's an issue with the emulator. Sorry for the inconvenience.

**Closed as completed by thagikura** 2015-11-04 07:03 UTC
