### ISSUE TITLE
Getting   Failure [INSTALL_FAILED_OLDER_SDK] error

### ISSUE THREAD

**Issue by Anushak5248** [googlesamples/android-FingerprintDialog#5] opened 2015-06-16 08:11 UTC
Hi,
I want to know about the biometric fingerprint so, when Im run this application Im unable to install. It shows me below error
pkg: /data/local/tmp/com.example.android.fingerprintdialog
Failure [INSTALL_FAILED_OLDER_SDK]
Even I have changed build .gradle file
compileSdkVersion "android-MNC"
buildToolsVersion "22.0.1"
defaultConfig {
minSdkVersion 15
maxSdkVersion 17
versionCode 1
versionName "1.0"
}
I want to check the functionality but im unable to get apk file
Please help me on this

**Comment by yanislavm** [comment] 2015-06-16 08:16
Hi,
You have to run it on Android M - for the moment on emulator or if you have a Nexus device with Android M image on it

Kind Regards

**Comment by Anushak5248** [comment] 2015-06-16 08:23
Hi Flymanj,
Thanks for your reply..
We don't have Android device with the version of Android M. If I have created android M emulator how can test fingerprint?. Is this application is not supported for below android M version?

**Comment by yanislavm** [comment] 2015-06-16 08:34
Hi,
I'm using emulator.
Please check that page - https://developer.android.com/preview/api-overview.html#authentication
There you can find that there is an adb command - adb -e emu finger touch <finger_id>
The problem is that you are not able to test a wrong finger print, or at least I was not able to find out a way.

Kind Regards,
Yanislav

**Comment by Anushak5248** [comment] 2015-06-16 12:06
Hi,
Thanks for your support..
I have created Android M emulator and successfully installed application
Unable to find the fingerprint sensor in my emulator[settings ->security->fingerprint-> password]
How can I take the finger print sensor by using emulator?..
And how can we get the finger_id [adb -e emu finger touch <finger_id>]
I 'm run below command but I haven't achieved.
adb -e emu finger touch
![emulator](https://cloud.githubusercontent.com/assets/12894806/8184259/0ed1cc2a-145b-11e5-848c-dcdd3b2f4174.png)

**Comment by yanislavm** [comment] 2015-06-16 20:35
Hi,
You are missing the "touch id". Sorry didn't noticed that it is removed because the brackets
try to type adb -e emu finger touch 1

Kind Regards

**Comment by Anushak5248** [comment] 2015-06-17 05:36
Hi,
Ok..But my system doesn't have touch screen :(.  I couldn't found any way to test this..

**Comment by thereisaway** [comment] 2015-08-21 15:06
Hi, for me, adb -e emu finger touch 1 does not work, nothing happened...

**Comment by codingjeremy** [comment] 2019-09-06 15:52
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!

**Closed as completed by codingjeremy** 2019-09-06 15:52 UTC
